/* File automatically generated by scripts/gen_opcode.py. */
#ifndef OPCODE_H
#define OPCODE_H

/* opcode listing */
enum {
    OP_HALT =  0,
    OP_ADD =  1,
    OP_SUB =  2,
    OP_PRINT =  3,
    OP_JMP =  4
};

#define OP_LABELS &&OP_HALT, &&OP_ADD, &&OP_SUB, &&OP_PRINT, &&OP_JMP, \


struct instruction {
    const char *name;
    int opcode;
    int has_op1;
    int has_op2;
    int has_result;
};

static const struct instruction instrs[] = {
    {"halt", OP_HALT,  0,  0,  0},
    {"add", OP_ADD,  1,  1,  1},
    {"sub", OP_SUB,  1,  1,  1},
    {"print", OP_PRINT,  1,  0,  0},
    {"jmp", OP_JMP,  1,  0,  0},
    {NULL, 0}
};

#endif /* OPCODE_H */
